remote_theme: pmarsceill/just-the-docs
theme: just-the-docs
# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
    "sql-select-ts on GitHub":
        - "https://lucasavila00.github.io/sql-select-ts/"
