remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
    "sql-select-ts on GitHub":
        - "https://github.com/lucasavila00/sql-select-ts"

plugins:
    - jekyll-remote-theme
